spring.application.name=spring-mail-demo


# Gmail SMTP settings
#spring.mail.host=smtp.gmail.com
## Use 587 for TLS or 465 for SSL
#spring.mail.port=465
#spring.mail.username=evad.se.dev
## Use the generated App Password
#spring.mail.password=trci txmd erwo ggzj


# Gmail SMTP settings
spring.mail.host=smtp.gmail.com
# Use 587 for TLS or 465 for SSL
spring.mail.port=587
spring.mail.username=evad.se.dev@gmail.com
spring.mail.password=

# Required properties for authentication and security
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional properties
# spring.mail.properties.mail.smtp.connectiontimeout=5000
# spring.mail.properties.mail.smtp.timeout=5000
# spring.mail.properties.mail.smtp.writetimeout=5000


# Optional properties
# spring.mail.properties.mail.smtp.connectiontimeout=5000
# spring.mail.properties.mail.smtp.timeout=5000
# spring.mail.properties.mail.smtp.writetimeout=5000

value.from.file=000000000000000000000


## Your app password for your device
# trci txmd erwo ggzj

