spring.application.name=sb-jpa-liquibase

spring.datasource.url=jdbc:postgresql://localhost:5432/neurowatch
spring.datasource.username=${POSTGRES_USER:neurowatch_user}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate is disabled because Liquibase will manage schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml