plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.11-SNAPSHOT'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.se.sample'
version = '0.0.1-SNAPSHOT'
description = 'demo'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation group: 'org.apache.solr', name: 'solr-solrj', version: '9.10.1'

    implementation group: 'org.eclipse.jetty.http2', name: 'http2-client', version: '10.0.13'
    implementation group: 'org.eclipse.jetty.http2', name: 'http2-common', version: '10.0.13'
    implementation group: 'org.eclipse.jetty.http2', name: 'http2-hpack', version: '10.0.13'
    implementation group: 'org.eclipse.jetty.http2', name: 'http2-http-client-transport', version: '10.0.13'
    implementation group: 'org.eclipse.jetty', name: 'jetty-util', version: '10.0.13'
    implementation group: 'org.eclipse.jetty', name: 'jetty-io', version: '10.0.13'
    implementation group: 'org.eclipse.jetty', name: 'jetty-http', version: '10.0.13'
    implementation group: 'org.eclipse.jetty', name: 'jetty-client', version: '10.0.13'
    implementation group: 'org.eclipse.jetty', name: 'jetty-alpn-client', version: '10.0.13'
    implementation group: 'org.eclipse.jetty', name: 'jetty-alpn-java-client', version: '10.0.13'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
